In [ ]:
import pandas as pd

In [3]:
essayAI = pd.read_csv('ai_manual_data.csv')
essayHuman = pd.read_csv('human_data_general.csv')
df_Hu = essayHuman.copy()
df_AI = essayAI.copy()

In [5]:
df_Hu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   text            3000 non-null   object
 1   title           3000 non-null   object
 2   label           3000 non-null   int64
 3   source_license  3000 non-null   object
dtypes: int64(1), object(3)
memory usage: 93.9+ KB

In [7]:
df_Hu.head()

,text,title,label,source_license
0,Background: Thyroid hormone sensitivity has em...,Association between thyroid hormone sensitivit...,0,CC-BY (PLOS)
1,Background: The prevalence of Type II diabetes...,Exploring the acceptability and attitude towar...,0,CC-BY (PLOS)
2,Identity abuse targets people on the basis of...,Identity abuse against sexual and gender minor...,0,CC-BY (PLOS)
3,Climate change poses significant risks to hum...,Health SDGs are at risk from climate change: E...,0,CC-BY (PLOS)
4,"In UAV aerial photography scenarios, targets ...",Aerial small target detection algorithm based ...,0,CC-BY (PLOS)

In [9]:
df_Hu['Text'] = df_Hu['text']
df_Hu = df_Hu.drop(columns= ['text', 'title', 'label', 'source_license'])
df_Hu.head()

                                                Text
0  Background: Thyroid hormone sensitivity has em...
1  Background: The prevalence of Type II diabetes...
2   Identity abuse targets people on the basis of...
3   Climate change poses significant risks to hum...
4   In UAV aerial photography scenarios, targets ...

In [11]:
df_Hu['Author'] = 'Human'
df_Hu.head()

                                                Text Author
0  Background: Thyroid hormone sensitivity has em...  Human
1  Background: The prevalence of Type II diabetes...  Human
2   Identity abuse targets people on the basis of...  Human
3   Climate change poses significant risks to hum...  Human
4   In UAV aerial photography scenarios, targets ...  Human

In [13]:
len(df_Hu.Text.unique())

3000

In [15]:
len(df_AI.text.unique())

3611

In [17]:
df_AI.head()

,text,label,source
0,This paper introduces a novel Graph Neural Net...,1,AI Generated (Gemini Studio)
1,We propose a new detection methodology for axi...,1,AI Generated (Gemini Studio)
2,"As 6G networks approach deployment, ultra-low ...",1,AI Generated (Gemini Studio)
3,CRISPR-Cas9 gene editing remains limited by of...,1,AI Generated (Gemini Studio)
4,Deciphering lost languages has traditionally r...,1,AI Generated (Gemini Studio)

In [21]:
df_AI = df_AI.drop_duplicates(keep= False)
df_AI['Text'] = df_AI['text']
df_AI = df_AI.drop(columns= ['text', 'label', 'source'])
df_AI['Author'] = 'AI'
df_AI.head()

KeyError: 'text'

In [21]:
df_AI.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3069 entries, 0 to 4970
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    3069 non-null   object
 1   Author  3069 non-null   object
dtypes: object(2)
memory usage: 71.9+ KB

In [23]:
df_Hu.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Text    3000 non-null   object
 1   Author  3000 non-null   object
dtypes: object(2)
memory usage: 47.0+ KB

In [25]:
df = pd.concat([df_AI, df_Hu], ignore_index= True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)
df.head()

                                                Text Author
0  This study investigates the chemical compositi...     AI
1  This study explores the cultural history of oi...     AI
2   Isolation of human peripheral blood mononucle...  Human
3   Dynamic Bayesian Networks (DBNs) are probabil...  Human
4   Within volleyball, performance analysis is em...  Human

In [51]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    6069 non-null   object
 1   Author  6069 non-null   object
dtypes: object(2)
memory usage: 95.0+ KB

In [ ]:
df.to_csv('')